version: '3.9'

services:

  db_mysql:
    container_name: db_mysql
    build: ./database
    ports:
      - "13306:3306"

  patient:
    container_name: patient
    build: ./
    ports:
      - "881:8081"
    depends_on:
      - db_mysql
    environment:
      spring.datasource.url: "jdbc:mysql://db_mysql:3306/bdd_mediscreen"

